
name: PR Validation

on:
  pull_request:
    branches: [ mainline ]

jobs:
  reviewer-assignment:
    name: Assign Reviewers
    runs-on: ubuntu-18.04
    steps:
      - name: Add Project Owner as Reviewer
        uses: kentaro-m/auto-assign-action@v1.1.1
        with:
          configuration-path: ".github/reviewer_config.yml"
  test:
    name: Build and Test
    runs-on: ubuntu-18.04
    container: elixir:1.10.4-alpine
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Install Hex
        run: mix local.hex --force

      - name: Install Rebar
        run: mix local.rebar --force

      - name: Install Dependencies
        run: mix deps.get --force

      - name: Run Tests
        run: mix coveralls.html

      - name: Publish Coverage Results
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: cover/excoveralls.html
